import type { ExtensionAPI, ExtensionContext } from "@mariozechner/pi-coding-agent";

function quoteForShellDoubleQuotes(text: string): string {
	const escaped = text.replace(/[\\"$`]/g, "\\$&");
	return `"${escaped}"`;
}

type ToolCallLike = {
	toolName?: string;
	input?: Record<string, unknown>;
};

function getModelLabel(ctx: ExtensionContext): string {
	const provider = ctx.model?.provider?.trim();
	const id = ctx.model?.id?.trim();
	if (provider && id) return `${provider}/${id}`;
	if (id) return id;
	if (provider) return provider;
	return "unknown model";
}

function ensureDisclosure(text: string, ctx: ExtensionContext, kind: "comment" | "pr"): string {
	const trimmed = text.trimEnd();
	if (!trimmed) return text;
	if (/\*This (comment|PR description) was generated by Pi using .+\*$/.test(trimmed)) return text;

	const model = getModelLabel(ctx);
	const disclosure =
		kind === "pr"
			? `*This PR description was generated by Pi using ${model}*`
			: `*This comment was generated by Pi using ${model}*`;
	return `${trimmed}\n\n${disclosure}`;
}

function isGitHubApiCommentToolCall(event: ToolCallLike): boolean {
	if (event.toolName !== "bash") return false;
	const command = String(event.input?.command || "");
	return /\bgh\s+api\b/.test(command) && /\/comments?(?:["' ]|$)|\/replies(?:["' ]|$)/.test(command);
}

function isGitHubPrCreateToolCall(event: ToolCallLike): boolean {
	if (event.toolName !== "bash") return false;
	const command = String(event.input?.command || "");
	return /\bgh\s+pr\s+create\b/.test(command);
}

function patchGhApiCommand(command: string, ctx: ExtensionContext): string {
	const bodyMatch = command.match(/-f\s+body=("([\s\S]*?)"|'([\s\S]*?)')/);
	if (!bodyMatch) return command;
	const quoted = bodyMatch[1];
	const rawBody = bodyMatch[2] ?? bodyMatch[3] ?? "";
	const nextBody = ensureDisclosure(rawBody, ctx, "comment");
	if (nextBody === rawBody) return command;
	return command.replace(quoted, quoteForShellDoubleQuotes(nextBody));
}

function patchGhPrCreateCommand(command: string, ctx: ExtensionContext): string {
	const bodyMatch = command.match(/--body\s+("([\s\S]*?)"|'([\s\S]*?)')/);
	if (!bodyMatch) return command;
	const quoted = bodyMatch[1];
	const rawBody = bodyMatch[2] ?? bodyMatch[3] ?? "";
	const nextBody = ensureDisclosure(rawBody, ctx, "pr");
	if (nextBody === rawBody) return command;
	return command.replace(quoted, quoteForShellDoubleQuotes(nextBody));
}

export default function githubDisclosure(pi: ExtensionAPI) {
	pi.on("tool_call", async (event, ctx) => {
		if (event.toolName !== "bash") return;

		const input = event.input as Record<string, unknown> | undefined;
		const command = typeof input?.command === "string" ? input.command : undefined;
		if (!command) return;

		if (isGitHubApiCommentToolCall(event)) {
			const nextCommand = patchGhApiCommand(command, ctx);
			if (nextCommand !== command) {
				input.command = nextCommand;
			}
			return;
		}

		if (isGitHubPrCreateToolCall(event)) {
			const nextCommand = patchGhPrCreateCommand(command, ctx);
			if (nextCommand !== command) {
				input.command = nextCommand;
			}
		}
	});
}
